[build]
  command = "pnpm run build"
  functions = "netlify/functions"
  publish = ".next"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "pnpm run dev"
  port = 3000
